### ISSUE TITLE
能支持linux不？是不是有什么问题？

### ISSUE THREAD

**Issue by iniwf** [windosx/face-engine#1]

**Comment by windosx** [comment]
是的，linux环境下使用cgo编译动态链接库时报了一个错误，我正在解决

**Comment by linwenchao** [comment]
> 是的，linux环境下使用cgo编译动态链接库时报了一个错误，我正在解决

请问下Linux版有什么进展吗？🍻

**Comment by kkmg112400** [comment]
@windosx 我已经搞了linux的 cgo 调用  ，有时间我单独建一个仓库写个例子吧。

**Comment by windosx** [comment]
@HuiguoRose 嗯，下半年公司事情较多，现在有时间了准备把SDK版本更新到2.2同时把Linux版本补上

**Comment by windosx** [comment]
@iniwf @linwenchao @HuiguoRose 新版本已提交
