### ISSUE TITLE
无法编译通过

### ISSUE THREAD

**Issue by qinjinze** [windosx/face-engine#12]
H:\project\src\ai\windosx\face-engine\cmd>go build -o test github.com/windosx/face-engine/cmd
# github.com/windosx/face-engine
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -larcsoft_face_engine
collect2.exe: error: ld returned 1 exit status

**Comment by windosx** [comment]
@qinjinze 虹软的库文件是否放到mingw目录下的lib中了？
