### ISSUE TITLE
目前报这个错误，该怎么解决呢，求回答

### ISSUE THREAD

**Issue by Chy19980831** [windosx/face-engine#14]
# github.com/windosx/face-engine/v4
C:\Users\�º���\AppData\Local\Temp\go-build647411330\b036\_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFGetActiveDeviceInfo':
/tmp/go-build/cgo-gcc-prolog:179: undefined reference to `ASFGetActiveDeviceInfo'
C:\Users\�º���\AppData\Local\Temp\go-build647411330\b036\_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFGetFaceLandMark':
/tmp/go-build/cgo-gcc-prolog:258: undefined reference to `ASFGetFaceLandMark'
C:\Users\�º���\AppData\Local\Temp\go-build647411330\b036\_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFGetMask':
/tmp/go-build/cgo-gcc-prolog:338: undefined reference to `ASFGetMask'
C:\Users\�º���\AppData\Local\Temp\go-build647411330\b036\_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFImageQualityDetect':
/tmp/go-build/cgo-gcc-prolog:385: undefined reference to `ASFImageQualityDetect'
C:\Users\�º���\AppData\Local\Temp\go-build647411330\b036\_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFOfflineActivation':
/tmp/go-build/cgo-gcc-prolog:427: undefined reference to `ASFOfflineActivation'
C:\Users\�º���\AppData\Local\Temp\go-build647411330\b036\_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFSetFaceShelterParam':
/tmp/go-build/cgo-gcc-prolog:542: undefined reference to `ASFSetFaceShelterParam'
C:\Users\�º���\AppData\Local\Temp\go-build647411330\b036\_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFUpdateFaceData':
/tmp/go-build/cgo-gcc-prolog:606: undefined reference to `ASFUpdateFaceData'
collect2.exe: error: ld returned 1 exit status

**Comment by windosx** [comment]
检查gcc版本是否高于4.8.2，另外，链接库目录中的虹软SDK版本是否为4.x
