### ISSUE TITLE
运行例子报了几个未定义的错，请问怎么解决

### ISSUE THREAD

**Issue by hiifong** [windosx/face-engine#19]
![image](https://user-images.githubusercontent.com/89133723/151021798-33ec8d71-9fe3-4b10-85c3-4ee1df54025c.png)

Linux，go1.17.6，gcc9.3.0.

**Comment by windosx** [comment]
从图上来看你使用的动态库应该是4.1的，抱歉抱歉，年底公司事务较多暂时还未适配

**Comment by hiifong** [comment]
谢谢大佬
