### ISSUE TITLE
请问支持视频流识别么？

### ISSUE THREAD

**Issue by 39499740** [windosx/face-engine#2]
如题，windows或linux都行

**Comment by windosx** [comment]
@39499740 官方文档中说明了支持的颜色空间有 RGB、NV12、NV21、I420、YUYV，我的示例代码中只给出了图片的，当然也可以是视频流，只需要处理好颜色格式即可。

**Comment by 39499740** [comment]
能提供一个人脸比对的DEMO么？麻烦你了

**Comment by windosx** [comment]
@39499740 计划新开一个项目，配合gocv来做一个视频流处理的示例

**Comment by windosx** [comment]
@39499740 [示例代码](https://github.com/windosx/arcface-gocv-examples)
