### ISSUE TITLE
请问有改造3.0的想法么

### ISSUE THREAD

**Issue by myzerg** [windosx/face-engine#4]
最近按照您的方法去做3.0版的SDK，问题太多了，做不下去

**Comment by windosx** [comment]
@myzerg 有这个计划，这段时间公司事务太多，有空了再搞。你遇到啥问题了可以发出来讨论一下，如果你先搞出来了欢迎pr。

**Comment by windzhu** [comment]
有兴趣的兄弟，一起研究学习3.0版

**Comment by sunnycamel** [comment]
我刚提交了一个pu， @windosx 审核merge一下就适配3.0了

**Comment by windosx** [comment]
@sunnycamel 非常感谢！已经合并到master，tag新增v3。
