### ISSUE TITLE
go get wrong

### ISSUE THREAD

**Issue by theonewang** [windosx/face-engine#5]
i use  go mod. this is some wrong below when i go get github.com/windosx/face-engine/v2:

go: downloading github.com/windosx/face-engine/v2 v2.2.0
verifying github.com/windosx/face-engine/v2@v2.2.0: checksum mismatch
        downloaded: h1:jlpz+XzYZVuc+zIBhJ7T7ed/T7ldsz+prZEXRfg2Q1k=
        sum.golang.org: h1:TxPBwZUWnG6PsR+cxfELUsrjp6rWSN83Uqvk7XndEQY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

-------------------------------------------------
wish to know how to solve ,thank u

**Comment by windosx** [comment]
@theonewang its like seems to be a local resources problem. try to delete "$GOPATH/src/github.com/windosx/face-engine" dir and "$GOPATH/pkg/mod/github.com/windosx/face-engine". then try to go get again.
the reason of this issue may be i rebuild the go mod version that doesnt match ur local version.
