### ISSUE TITLE
提取人脸特征的时候，咋感觉arr没有赋值呢？

### ISSUE THREAD

**Issue by BlackShiningBird** [windosx/face-engine#8]
怎么将go struct 转为 C struct? 提取人脸特征的时候，咋感觉arr没有赋值呢？
![截图2](https://user-images.githubusercontent.com/42290246/89601481-38090d00-d897-11ea-9651-2a3c5ea6e72c.png)

**Comment by windosx** [comment]
arr是指向非托管内存的指针，ps里存放的才是特征数组。我已经提交新版本了，这个方法用go结构体代替原C结构体的返回参数，同时需要在FaceFeature结构体不再使用时调用它的Release方法以释放非托管内存所占空间。
