### ISSUE TITLE
一个因为人脸特征提取失败导致panic的bug

### ISSUE THREAD

**Issue by t924417424** [windosx/face-engine#9]
首先感谢作者将虹软的sdk绑定到go，在今天偶发的一个bug，在engine.go的第296行
`byteArr := (*[1 << 28]byte)(unsafe.Pointer(asfFaceFeature.feature))[:height:height]       //如果图片中的人脸特征提取失败会导致asfFaceFeature.feature为nil，从而导致这里抛出panic，对应虹软sdk的错误代码为：81925`

可通过修改为以下代码，或在提取特征逻辑中加入判断是否为nil的逻辑来解决
`byteArr := (*[1 << 28]byte)(unsafe.Pointer(asfFaceFeature.feature))               //删除[:height:height]`

**Comment by windosx** [comment]
@t924417424 感谢反馈！已修复！
